config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "restaurants#index"
  resources :restaurants do
    resources :reviews
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, presence: true
  validates :location, presence: true
  has_many :reviews, dependent: :destroy

end

app/models/review.rb
class Review < ApplicationRecord
  validates :description, presence: true
  belongs_to :restaurant
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :reviews
  # has_many :votes     
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

 protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
 end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @restaurants = Restaurant.all.order(name: :asc)
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new
    @reviews = @restaurant.reviews.order(created_at: :desc)
  end

  def new
    @restaurant = Restaurant.new
  end

  def edit #displays edit page
    @restaurant = Restaurant.find(params[:id])
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to @restaurant, notice: 'Successfully posted restaurant'
    else
      render action: 'new'
    end
  end

  def update  #note update vs. edit above
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant
    else
      render 'edit'
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy

    redirect_to restaurants_path
  end

private

  def restaurant_params
    params.require(:restaurant).permit(:name, :location, :description)
  end
end

  # def authorize_user
  #   if !user_signed_in? || !current_user.admin?
  #     raise ActionController::RoutingError.new("Not Found")
  #   end
  # end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  
  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant #assigning the restaurant to the review

    if @review.save
      redirect_to restaurant_path(@restaurant), notice: 'Review posted successfully'
    else
      flash[:notice] = 'Failed to save review'
      flash[:error] = @review.errors.full_messages(", ")

      redirect_to @restaurant
    end
  end

  def edit
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.find(params[:id])
    if @review.update(review_params)
      redirect_to @restaurant
    else
      render 'edit'
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.find(params[:id])
    @review.destroy

    redirect_to @restaurant
  end

private
  def review_params
    params.require(:review).permit(:description, :restaurant_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RestaurantReview</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav>
      <ul>
        <% if user_signed_in? %>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
          <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
        <% else  %>
          <li><%= link_to 'Log In', new_user_session_path %></li>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>


    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for(restaurant) do |f| %>
  <% if restaurant.errors.any? %>
    <div id="error_explanation">
      <h3>
        <%= pluralize(restaurant.errors.count, "error") %> prohibited
        this restaurant from being saved:
      </h3>
      <ul>
        <% restaurant.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Edit Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Back', restaurants_path %>
<%= link_to 'Delete', restaurant_path(@restaurant),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>
<ul>
  <% @restaurants.each do |restaurant| %>
    <li><%= link_to restaurant.name, restaurant_path(restaurant.id) %> <%= restaurant.location %></li>
  <% end %>
</ul>


<%= link_to 'Post New Restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>
<%= render 'form', restaurant: @restaurant %>
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<h3><%= @restaurant.name %></h3>

<p>Location: <%= @restaurant.location %></p>
<p>Description: <%= @restaurant.description %></p>

<h3>Reviews</h3>
<ul>
  <% @reviews.each do |review| %>
    <li><%= review.description %>
      <%= link_to 'Edit', edit_restaurant_review_path(@restaurant, review) %> |
      <%= link_to 'Delete', restaurant_review_path(review),
      method: :delete,
      data: { confirm: 'Are you sure?' } %>
    </li>
  <% end %>
</ul>

<h3>Post Review</h3>
<%= form_for([@restaurant, @review]) do |f| %>

  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h3>
        <%= pluralize(@review.errors.count, "error") %> prohibited
        this review from being saved:
      </h3>
      <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %> |
<%= link_to 'Delete', restaurant_path(@restaurant),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>

app/views/reviews/edit.html.erb
<h1>Edit Review for <%= @restaurant.name %></h1>

<%= form_for([@restaurant, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h3>
        <%= pluralize(@review.errors.count, "error") %> prohibited
        this review from being saved:
      </h3>
      <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit "Update Review" %>
  </div>
<% end %>


<%= link_to 'Back', restaurant_path(@restaurant) %>
<%= link_to 'Delete', restaurant_path(@restaurant),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>